### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by tichalik** [marty1885/eoparser#1]
Hi! I've been trying to use Your software, however i come across several errors while running it. First is the problem with reading the file -- I managed to determine it's because under Windows 10 (at least my configuration) and Python 3.11 the `open()` function defaults to interpreting the file as cp1252 instead of utf-8. Adding the parameter so that line 53 at `eoparser.py` looks like 

    `f = open(path, encoding = "utf-8")

fixes the problem and makes the program independent from the locale default encoding. Unfortunately then the demo spits out 

![image](https://user-images.githubusercontent.com/72296361/225101406-db2a96dc-4b1f-4926-b8d8-2bfb8bfd3c61.png)

I imagine it's because some problem with termcolor. I'm using version 2.2.0 and the `colored` function produces such gibberish.

**Comment by marty1885** [comment]
Hi, I've pushed the fix for loading the dictionary. That should be working now.

The issue with display seems to be the fact that your terminal emulator does not support VT100 escape code. By the looks of it, you are using the default console on Windows 10. If that's the case, it is expected. Can you try the built-in terminal on VSCode or use [Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701)?

Windows Terminal:
![圖片](https://user-images.githubusercontent.com/8792393/225198825-44668a44-8fc6-49fb-afd4-79f161e77bfb.png)

Default console on Windows 10:
![圖片](https://user-images.githubusercontent.com/8792393/225198779-616962f7-a154-4307-bfd7-6abc2699e99d.png)

**Comment by tichalik** [comment]
Hi, thanks a lot, using the cmd app you provided makes everything work fine.

**Comment by marty1885** [comment]
I added a workaround to enable VT100 on Windows. i can't find an official way. But it should work on the default console now. 
![圖片](https://user-images.githubusercontent.com/8792393/225247079-358d6692-c801-4bac-a0b6-72f9cde40c3e.png)

**Comment by marty1885** [comment]
@tichalik Thanks for reporting. I think the latest code should solve your issues. I'm closing the issue. Feel free to reopen it if they still appears.
